easy_admin:
    site_name: 'SF Talk rating app'
    user:
        display_name: true
        display_avatar: false

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i'

    entities:
        Event:
            class: App\Entity\Event
            label: "SF Events"
            list:
                fields: ['name', 'startDate', 'endDate', 'status']
                sort: 'endDate'
                actions:
                    - { name: 'admin_event_scrape_init', label: 'Scrape schedule', type: 'route' }
            form:
                fields:
                    - 'name'
                    -
                        property: 'status'
                        type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
                        type_options:
                            choices:
                                Draft: 'draft'
                                Online: 'online'
                    - { property: 'startDate', type_options: { widget: 'single_text' } }
                    - { property: 'endDate', type_options: { widget: 'single_text' } }
                    - { property: 'badgeUrl', type: 'Symfony\Component\Form\Extension\Core\Type\UrlType' }

        Talk:
            class: App\Entity\Talk
            label: Talks
            list:
                fields:
                    -
                        property: 'event.name'
                        label: 'Event'
                    - 'title'
                    -
                        property: 'speaker.name'
                        label: 'Speaker'
            form:
                fields:
                    -
                        property: 'event'
                        type: 'Symfony\Bridge\Doctrine\Form\Type\EntityType'
                        type_options:
                            class: App\Entity\Event
                            choice_label: 'name'
                    - 'title'
                    - 'description'
                    -
                        property: 'speaker'
                        type: App\Form\SpeakerType
                    -
                        property: 'firstTimeSpeaker'
                        type: 'Symfony\Component\Form\Extension\Core\Type\CheckboxType'

        EventReview:
            class: App\Entity\EventReview
            label: "Event reviews"
            list:
                actions: ['show', '-add', '-search', '-delete']
                fields:
                    -   property: 'event.name'
                        label: 'Event'
                    -   property: 'author.name'
                        label: 'Author'
                    -
                        property: 'rating'
                        label: 'Rating (/5)'
                    - 'postedAt'
                    - 'status'
                sort: 'postedAt'
            show:
                actions: ['-delete']
                fields:
                    -
                        property: 'event'
                        label: 'About event'
                    - 'status'
                    -
                        property: 'rating'
                        label: 'Rating (/5)'
                    - 'comment'
                    -
                        property: 'prettyHighlights' # Virtual
                        label: 'Highlights'
                    -   property: 'contentRating'
                        label: 'Content rating (/5)'
                    -   property: 'locationRating'
                        label: 'Location rating (/5)'
                    -   property: 'foodRating'
                        label: 'Food rating (/5)'
                    -   property: 'socialEventRating'
                        label: 'Social event rating (/5)'
                    - 'postedAt'
                    -
                        property: 'author.name'
                        label: 'Author public name'
                    -   property: 'author.username'
                        label: 'Author username'
                    -
                        property: 'author.uuid'
                        label: 'Author UUID'
                    -
                        property: 'author.email'
                        label: 'Author email'
            form:
                fields:
                    -
                        property: 'status'
                        type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
                        type_options:
                            choices:
                                Pending moderation: 'pending_moderation'
                                Online: 'online'
                                Refused: 'refused'

        TalkReview:
            class: App\Entity\TalkReview
            label: "Talk reviews"
            list:
                actions: ['show', '-add', '-search', '-delete']
                fields:
                    -   property: 'talk.name'
                        label: 'Talk'
                    -   property: 'author.name'
                        label: 'Author'
                    -
                        property: 'rating'
                        label: 'Rating (/5)'
                    - 'postedAt'
                    - 'status'
                sort: 'postedAt'
            show:
                actions: ['-delete']
                fields:
                    -
                        property: 'talk'
                        label: 'About talk'
                    - 'status'
                    -
                        property: 'rating'
                        label: 'Rating (/5)'
                    - 'comment'
                    -
                        property: 'prettyHighlights' # Virtual
                        label: 'Highlights'
                    -   property: 'contentRating'
                        label: 'Content rating (/5)'
                    -   property: 'deliveryRating'
                        label: 'Delivery rating (/5)'
                    -   property: 'relevanceRating'
                        label: 'Relevance rating (/5)'
                    - 'postedAt'
                    -
                        property: 'author.name'
                        label: 'Author public name'
                    -   property: 'author.username'
                        label: 'Author username'
                    -
                        property: 'author.uuid'
                        label: 'Author UUID'
                    -
                        property: 'author.email'
                        label: 'Author email'
            form:
                fields:
                    -
                        property: 'status'
                        type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
                        type_options:
                            choices:
                                Pending moderation: 'pending_moderation'
                                Online: 'online'
                                Refused: 'refused'
