imports:
    # We import users to pass to connect_memory provider (if we have a file).
    # Users key does not support environment variables, see https://github.com/symfony/symfony/issues/27683
    - { resource: ../../admins.yaml, ignore_errors: true }

security:
    providers:
        symfony_connect:
            connect_memory:
                users: []

    role_hierarchy:
        ROLE_ADMIN: ROLE_CONNECT_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            symfony_connect:
                check_path: symfony_connect_callback
                login_path: symfony_connect_login
                failure_path: home # TODO
                remember_me: false
                provider: symfony_connect
            logout:
                path: logout
                target: home
            anonymous: true

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/review, roles: [ROLE_CONNECT_USER] }
        - { path: ^/event, roles: [ROLE_CONNECT_USER] }
        - { path: ^/, roles: [] } # Home - all can see
