security:
    providers:
        symfony_connect:
            connect_memory:
                users:
                    37cd387c-d19e-4472-876a-8082ada2ca21: ROLE_ADMIN # Romaric Drigon
                    71e2f393-158c-4a1c-92c4-2234548e09f5: ROLE_ADMIN # Emilie Lorenzo
                    072fe4aa-78a1-45c7-b802-34eb632562ef: ROLE_ADMIN # Nicolas Grekas

    role_hierarchy:
        ROLE_ADMIN: ROLE_CONNECT_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            symfony_connect:
                check_path: symfony_connect_callback
                login_path: symfony_connect_login
                failure_path: home # TODO
                remember_me: false
                provider: symfony_connect
            logout:
                path: logout
                target: home
            anonymous: true

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/comment, roles: [ROLE_CONNECT_USER] }
        - { path: ^/, roles: [] } # Home - all can see
